apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-svc
  namespace: default
  labels:
    app: python-fastapi
spec:
  selector:
    app: python-fastapi
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP