apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    # 특정한 클래스를 지정하지 않아 k3s 기본 관리자가 처리하도록 함
    kubernetes.io/ingress.class: "" 
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-svc
            port:
              number: 80
      - path: /api/python-fastapi
        pathType: Prefix
        backend:
          service:
            name: python-fastapi-svc
            port:
              number: 8000